# Generated by Django 5.1.5 on 2025-01-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Название блюда"),
                ),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_number", models.SmallIntegerField(verbose_name="Номер стола")),
                ("total_price", models.IntegerField(verbose_name="Цена")),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "в ожидании"), (2, "готово"), (3, "оплачено")],
                        default=1,
                        verbose_name="Статус заказа",
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(to="orders.dish", verbose_name="Блюда"),
                ),
            ],
        ),
    ]
