# Generated by Django 5.1.5 on 2025-01-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"default_related_name": "order"},
        ),
        migrations.AlterField(
            model_name="dish",
            name="price",
            field=models.IntegerField(verbose_name="Цена"),
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_open", models.BooleanField(default=True)),
                (
                    "orders",
                    models.ManyToManyField(to="orders.order", verbose_name="Заказы"),
                ),
            ],
            options={
                "default_related_name": "shift",
            },
        ),
    ]
